name: Visual Studio for Mac

on: [push]

jobs:
  VSMac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0 # GitVersioning needs deep clone

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Restore
      run: mono /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll -t:Restore -p:Configuration=ReleaseMac

    - name: Build
      run: |
        mono /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/MSBuild.dll MonoDevelop.MSBuildEditor.sln -p:Configuration=ReleaseMac -p:CreatePackage=true

    - name: Download NUnit
      run: nuget install NUnit.ConsoleRunner -Version 3.11.1 -OutputDirectory testrunner

    - name: Test
      run: mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./MonoDevelop.MSBuild.Tests/bin/Release/MonoDevelop.MSBuild.Tests.dll

    - uses: actions/upload-artifact@v2
      with:
        name: MSBuild Editor for Visual Studio for Mac
        path: MonoDevelop.MSBuildEditor/bin/Release/net472/*.mpack