name: Visual Studio for Mac

on: [push]

jobs:
  VSMac:
    runs-on: macos-latest
    strategy:
      matrix:
        config: [ DebugMac ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0 # GitVersioning needs deep clone

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore -p:Configuration=${{ matrix.config }}

    - name: Build
      run: dotnet build --no-restore -c ${{ matrix.config }} -p:CreatePackage=true

    - name: Test
      run: dotnet test --no-build -c ${{ matrix.config }}

    - uses: actions/upload-artifact@v2
      with:
        name: MSBuild Editor for Visual Studio for Mac
        path: MonoDevelop.MSBuildEditor/bin/${{ matrix.config }}/net6.0/*.mpack