name: Visual Studio

on: [push]

jobs:
  VSWin:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [ Debug ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0 # GitVersioning needs deep clone

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Find MSBuild
      uses: microsoft/setup-msbuild@v1.1.0

    - name: Restore
      run: msbuild -t:Restore -p:Configuration=${{ matrix.config }}

    - name: Build
      run: msbuild MonoDevelop.MSBuildEditor.sln -p:Configuration=${{ matrix.config }}

    - name: Test
      run: dotnet test -c ${{ matrix.config }} --no-build

    - uses: actions/upload-artifact@master
      with:
        name: MSBuild Editor for Visual Studio
        path: MonoDevelop.MSBuild.Editor.VisualStudio/bin/Release/MonoDevelop.MSBuild.Editor.VisualStudio.*.vsix
