name: Visual Studio

on: [push]

jobs:
  VSWin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0 # GitVersioning needs deep clone

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Find MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore
      run: msbuild -t:Restore -p:Configuration=Release

    - name: Build
      run: |
        msbuild MonoDevelop.MSBuildEditor.sln -p:Configuration=Release -m -p:CreatePackage=true

    - name: Set up Nuget.exe
      uses: NuGet/setup-nuget@v1

    - name: Download NUnit
      run: nuget install NUnit.ConsoleRunner -Version 3.11.1 -OutputDirectory testrunner

    - name: Test
      run: .\testrunner\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console.exe .\MonoDevelop.MSBuild.Tests\bin\Release\MonoDevelop.MSBuild.Tests.dll

    - uses: actions/upload-artifact@master
      with:
        name: MSBuild Editor for Visual Studio
        path: MonoDevelop.MSBuild.Editor.VisualStudio/bin/Release/MonoDevelop.MSBuild.Editor.VisualStudio.*.vsix
